DATA:
 PATH: "D:\\data\\food_detection\\public_train\\images"
 ANNO: '../resource/df_anno_seg.pth'
 IMG_SIZE: 256
 BATCH_SIZE: 24
 NUM_WORKERS: 2
 INPUT_NAME: 'file_name'
 TARGET_NAME: 'segmentation'
TRAIN:
 EPOCHS: 10
 BASE_LR: 0.001
 WARMUP_LR: 0.0005
 WEIGHT_DECAY: 0.00001
 WARMUP_EPOCHS: 5  
 DECAY_EPOCHS: 5
 OPT_NAME: 'Adam'
 EPS: 0.00000001
 BETAS: [0.9, 0.999]
 MOMENTUM: 0.9
 FREQ_EVAL: 2
 SCH_NAME: 'step'
 LR_DECAY: 0.8 
 USE_EMA: True
 EMA_DECAY: 0.999